### ISSUE TITLE
 can't be downloaded

### ISSUE THREAD

**Issue by lifeng5658** [Hangover3832/ComfyUI-Hangover-Nodes#20]
The model can't be downloaded automatically. You don't specify which folder it should be placed in when manually downloading it. There's only a model name, and no matter where it's placed, it will be hard to find later on. There are too many files with this name.

**Comment by Hangover3832** [comment]
You cannot manually place the model somewhere, models are managed by the huggingface hub. Do you get error messages?

**Comment by Hangover3832** [comment]
@lifeng5658, the node has been updated and now supports manually downloaded models, see [README.md](/Hangover3832/ComfyUI-Hangover-Nodes/blob/main/README.md)

**Comment by lifeng5658** [comment]
I have downloaded all the required files and placed them in the models\kosmos2\kosmos-2-patch14-224 directory, the error is as follows:
Error occurred when executing MS kosmos-2 Interrogator:

'MsKosmos2' object has no attribute 'model'

File "E:\AI\ComfyUI-aki-v1.1\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\AI\ComfyUI-aki-v1.1\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "E:\AI\ComfyUI-aki-v1.1\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\AI\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-Hangover-Nodes\ms_kosmos2.py", line 89, in interrogate
if (self.model == None) or (self.processor == None) or (self.modelname != model) or (device != self.device):

=====================================================================

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\AI\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-Manager\extension-node-map.json
got prompt
kosmos2: loading model E:\AI\ComfyUI-aki-v1.1\models/kosmos2/kosmos-2-patch14-224, please stand by....
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\AI\ComfyUI-aki-v1.1\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\AI\ComfyUI-aki-v1.1\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\AI\ComfyUI-aki-v1.1\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\AI\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-Hangover-Nodes\ms_kosmos2.py", line 96, in interrogate
    self.model = AutoModelForVision2Seq.from_pretrained(model_path).to(dev)
  File "E:\AI\ComfyUI-aki-v1.1\python\lib\site-packages\transformers\models\auto\auto_factory.py", line 434, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "E:\AI\ComfyUI-aki-v1.1\python\lib\site-packages\transformers\models\auto\configuration_auto.py", line 873, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "E:\AI\ComfyUI-aki-v1.1\python\lib\site-packages\transformers\models\auto\configuration_auto.py", line 579, in __getitem__
    raise KeyError(key)
KeyError: 'kosmos-2'

Prompt executed in 0.56 seconds
got prompt
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\AI\ComfyUI-aki-v1.1\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\AI\ComfyUI-aki-v1.1\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\AI\ComfyUI-aki-v1.1\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\AI\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-Hangover-Nodes\ms_kosmos2.py", line 89, in interrogate
    if (self.model == None) or (self.processor == None) or (self.modelname != model) or (device != self.device):
AttributeError: 'MsKosmos2' object has no attribute 'model'

**Comment by lifeng5658** [comment]
I have downloaded the entire folder, which is about 13GB in total.

**Comment by Hangover3832** [comment]
> I have downloaded the entire folder, which is about 13GB in total.

Yeah but you don't need the pytorch_model.bin, the model.safetensor is sufficient, so you can save ~6GB.

What version of transformers do you have installed?
`E:\AI\ComfyUI-aki-v1.1\python\python.exe -m pip freeze | findstr "transformers"`

**Comment by zhenyuanzhou** [comment]
Error occurred when executing MS kosmos-2 Interrogator:

'MsKosmos2' object has no attribute 'model'

File "F:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
res_value = old_func(*final_args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Hangover-Nodes\ms_kosmos2.py", line 89, in interrogate
if (self.model == None) or (self.processor == None) or (self.modelname != model) or (device != self.device):

I have the same problem: the transformers version is 4.39.1
